"""Added blogs

Revision ID: 184f0475b00a
Revises: e3377a01e59e
Create Date: 2018-04-04 21:40:12.197009

"""

# revision identifiers, used by Alembic.
revision = '184f0475b00a'
down_revision = 'e3377a01e59e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_classes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blog_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blog_subclasses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('class_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['blog_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blogs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('view_counter', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('subclass_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['blog_sources.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['blog_subclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    op.drop_table('blog_subclasses')
    op.drop_table('blog_sources')
    op.drop_table('blog_classes')
    ### end Alembic commands ###
